### ISSUE TITLE
Publish 1.0.0 to npm ?

### ISSUE THREAD

**Issue by yubozhao** [jbmusso/gremlin-client#11]
In npm directory, it is still list as 0.3.1 right now.

**Comment by jbmusso** [comment]
It looks like `npm publish` failed somehow. I can't publish from here right now but I will look into it shortly.

Thanks for reporting this.

**Comment by yubozhao** [comment]
@jbmusso no worries, thx for the awesome package.

**Comment by jbmusso** [comment]
Thanks for the kind words. I need to fix an auth issue with npm, I will work on this asap. I'll also add proper git tags.

**Comment by jbmusso** [comment]
v1.0.0 is now published on npm. Let me know if something goes wrong.

https://www.npmjs.com/package/gremlin-client
