### ISSUE TITLE
Per-message processor ignored when using sessions

### ISSUE THREAD

**Issue by rjbriody** [jbmusso/gremlin-client#7]
In this example the processor will be ignored. 

```
var gremlinClient = gremlin.createClient(8182, 'localhost', {session: true});
gremlinClient.execute(script, null, {processor: 'willBeIgnored'}, callback);
```

The bug occurs on the following line, where the session processor is used despite the fact that the message.processor is already set.

https://github.com/jbmusso/gremlin-client/blob/develop/src/gremlinclient.js#L195

I believe it should be something more like this:

``` command.message.processor = (message.processor || (this.options.processor || 'session'));```

**Comment by jbmusso** [comment]
I see - I will fix this tonight and add unit tests.

On Thursday, March 5, 2015, bobb <notifications@github.com> wrote:

> In this example the processor will be ignored.
>
> var gremlinClient = gremlin.createClient(8182, 'localhost', {session: true});
> gremlinClient.execute(script, null, {processor: 'willBeIgnored'}, callback);
>
> The bug occurs on the following line, where the session processor is used
> despite the fact that the message.processor is already set.
>
>
> https://github.com/jbmusso/gremlin-client/blob/develop/src/gremlinclient.js#L195
>
> I believe it should be something more like this:
>
> command.message.processor = (message.processor || (this.options.processor
> || 'session'));
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jbmusso/gremlin-client/issues/7>.
>


-- 
Jean-Baptiste
