### ISSUE TITLE
Add LICENSE.txt

### ISSUE THREAD

**Issue by rjbriody** [jbmusso/gremlin-client#8]
It would be helpful if gremlin-client specified a license. It would be extra cool if that happened to be the Apache 2.0 license, but of course that is up to you :)

**Comment by jbmusso** [comment]
Ah - I thought it was under the MIT license. I didn't notice I didn't specify any.
I can't see anything wrong with the Apache 2.0, and it also makes a lot of sense to use the same license as the TinkerPop project. Fine by me!

**Comment by pluradj** [comment]
Any updates on the license decision?

**Comment by jbmusso** [comment]
It'll be MIT just like most JS libraries. I think it's compatible with Apache 2.0, I recall a discussion with @spmallette on this one.

I'll update it tonight.

**Comment by spmallette** [comment]
Before I'm accused of being a lawyer, I'll just add this: MIT Is on this list "white-listed" by Apache: http://www.apache.org/legal/resolved.html

**Comment by pluradj** [comment]
Thanks!
